"""empty message

Revision ID: 12f47be9624b
Revises: 11de67cc2c15
Create Date: 2024-06-27 23:34:54.487333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f47be9624b'
down_revision: Union[str, None] = '11de67cc2c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'film',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'instagram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'tiktok',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'you_tube',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'code',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('films', 'code',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('films', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'you_tube',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'tiktok',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'instagram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'film',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
